### ISSUE TITLE
Split into multiple files

### ISSUE THREAD

**Issue by flanaras** [syfantid/Greek-CS-Student-Opportunities#3]
Having a single file for everybody to work on seems like a hassle especially when you would like to merge stuff together (i.e. pull requests). I could be restructured in a per topic file basis, i.e. one file Graduate Positions, another for Travel Grants, etc.

PS. Instead of merge you can use [rebase](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) (where applicable) to keep a linear commit history.

**Comment by syfantid** [comment]
Thanks @flanaras for solving this issue! ;)
